# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z72t2ty9t0VYqTlffejBEVQKwESDDTwc
"""

import math
from scipy.stats import binom
import matplotlib.pyplot as plt
import array as arr
import numpy as np

p=0.5
#probability of getting an odd number on dice


n=6
#total number of throws


r_values = np.arange(n+1)


sample_size=100000

binom_dist=[binom.pmf(r, n, p) for r in r_values ] 

binomial_simulation = binom.rvs(n,p,size=sample_size)
#Array containing the simulated probability distribution for each value of r 

count=[0]*(n+1)
#array for count
prob=[0]*(n+1)



for i in range(sample_size):
  for j in range(n+1) :
     if binomial_simulation[i] == j:
       count[j]+=1


 
for k in range(n+1):
  prob[k]=count[k]/sample_size

for l in range(n+1):
  print("Pr(X=",l,")=",prob[l])
plt.bar(r_values, prob) 
plt.show()

probability_5=prob[5]
probability_6=prob[6]
print("A:Pr(X=5)")
print("Simulated probability of getting 5 successes : ",probability_5)
print("Theoretical probability of getting 5 successes:",6/64)
print("The absolute error",abs(probability_5-6/64),"is so small so we can conclude ", 6/64," as probability of getting 5 successes")


print("B:Pr(X>=5)")
print("simulated probability of getting at least 5 successes is ", probability_5+probability_6)
print("Theoretical probability of getting at least 5 successes is ", 7/64)
print("The absolute error",abs(probability_5+probability_6-7/64),"is so small so we can conclude ", 7/64," as probability of getting at least 5 successes")

print("C:Pr(X<=5)")
print("Simulated probability of getting at most 5 successes is:",1-probability_6)
print("Theoretical probability of getting at most 5 successes is ",63/64)
print("Absolute error in them is ",abs(1-probability_6-63/64),"which is so small so we can conclude",63/64,"as probabilty of getting at most 5 successes")
print("or")
probability__5=prob[0]+prob[1]+prob[2]+prob[3]+prob[4]+prob[5]
print("Simulated probability of getting at most 5 successes is:",probability__5)
print("Theoretical probability of getting at most 5 successes is ",63/64)
print("Absolute error in them is ",abs(probability__5-63/64),"which is so small so we can conclude",63/64,"as probabilty of getting at most 5 successes")